### ISSUE TITLE
Question on results

### ISSUE THREAD

**Issue by lynnetab** [CIA-Oceanix/GeoTrackNet#24]
Thank you for sharing your software.  I have re-run the example test data, ct_201701020310_30, and I am finding 26 anomalies.  The code ran to 80003 steps and had 100 missing data points. 

Question:
In your paper, "GeoTrackNet A Maritime Anomaly Detector using Probabilistic Neural Network Rep. of AIS Tracks and a Contrario Detection" you report than you found only 25 anomalies.  Please let me know if the software has been updated for this paper since I have 26 anomalies.

I would like to look at the SOG and COG for the anomalous vessels.  I have written code to plot each track individually but the SOG does not look correct when I read from the pickle test file.  Is v_sog = tmp[:,2]/float(onehot_sog_bins) correct?  I believe that the exact SPEED_MAX may not be available based on the data_preprocessing.py code.  Any suggestions on how to extract SOG or COG?
My goal is to understand the results.  Any suggestions would be appreciated.  I am will to share anything finding that I obtain.

Thank You

**Comment by duonginspace** [comment]
Hello @lynnetab ,

1) _"In your paper, "GeoTrackNet A Maritime Anomaly Detector using Probabilistic Neural Network Rep. of AIS Tracks and a Contrario Detection" you report than you found only 25 anomalies. Please let me know if the software has been updated for this paper since I have 26 anomalies._"
=> That is not shocking. Different hardware represents floating-point numbers differently, so we cannot guarantee that the results will always be identical. Are your 26 anomalies consistent with the 25 presented in the paper?

2) SPEED_MAX is 30 knots.

3) v_sog should be tmp[:,2]*SPEED_MAX/float(onehot_sog_bins) = tmp[:,2]*30/30.

4) v_cog should be tmp[:,3]*COG_MAX/float(onehot_cog_bins) = tmp[:,3]*360/72.

And yes, please share the results with us and the community.

**Comment by lynnetab** [comment]
I was able to run the GeoTrackNet software after following the instructions and using the provided datasets. Here are my notes:

- python 3.6.10
- Install relevant python libraries requirements file (conda env update -v --file requirements.yml)
- Ran the code with 1 CPU and 1 GPU. 
- Ran the code uses the steps provide on summary page along with the test, training, and validation data sets: ct_2017010203_10_20/ct_2017010203_10_20_test.pkl, ct_2017010203_10_20/ct_2017010203_10_20_train.pkl and ct_2017010203_10_20/ct_2017010203_10_20_valid.pkl

Results:
I had the following 26 MMSI identified as abnormal.  
[Abnormal_tracks-ct_2017010203_10_20_train.pkl-ct_2017010203_10_20_test.pkl-latent_size-100-step-80003-eps-1e-10-26.csv](https://github.com/user-attachments/files/16074408/Abnormal_tracks-ct_2017010203_10_20_train.pkl-ct_2017010203_10_20_test.pkl-latent_size-100-step-80003-eps-1e-10-26.csv)
![Abnormal_tracks2-ct_2017010203_10_20_train pkl-ct_2017010203_10_20_test pkl-latent_size-100-step-80003-eps-1e-10-26](https://github.com/CIA-Oceanix/GeoTrackNet/assets/5273464/b01d6382-3634-4120-b187-286d796bb804)
![Uploading Abnormal_tracks-ct_2017010203_10_20_train.pkl-ct_2017010203_10_20_test.pkl-latent_size-100-step-80003-eps-1e-10-26.png…]()
